---
version: '3'
services:
  mydb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: intelliqit

  mywordpress:
    image: wordpress
    ports:
      - 8080:80
    deploy:
      replicas: 3
...
